import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import '@/styles/globals.css';
import AppLayout from '@/components/layout/AppLayout';
import { ThemeProvider } from 'next-themes';
import AppProvider from '@/components/providers/AppProvider';

const outfitSans = Outfit({
  variable: '--font-outfit-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${outfitSans.variable} min-h-screen antialiased scroll-smooth`}
      >
        <AppProvider>
          <AppLayout>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              {children}
            </ThemeProvider>
          </AppLayout>
        </AppProvider>
      </body>
    </html>
  );
}
